### ISSUE TITLE
Small Crash, Can’t get it to work

### ISSUE THREAD

**Issue by ChipsDahCat** [PretendoNetwork/.github#24]
When I open the Nimbus app on my New 2DS XL, I get the usual menu. I try to tap on the Pretendo option, and guess what. Crash. It leaves me on Nintendo, and It kinda sucks.

**Comment by Agggelosio** [comment]
Like what exactly can tou provide more info? I am not involed in the pretendo project but i will try to help

**Comment by ChipsDahCat** [comment]
Well, when I open the Pretendo app on my New 2DS XL, it just exits out of it.Sent from my iPadOn Jun 2, 2023, at 9:56 AM, Agggelosio ***@***.***> wrote:﻿
Like what exactly can tou provide more info? I am not involed in the pretendo project but i will try to help

**Comment by grayhax** [comment]
> Like what exactly can tou provide more info? I am not involed in the pretendo project but i will try to help

I am experiencing the same issue, I load Homebrew Launcher, Load Nimbus, Select Pretendo, And then it crashes. When I check Nimbus, It just stays as "Nintendo Network Loaded". Any solutions?

**Comment by Jandri555** [comment]
Same here :(

**Comment by ilonachan** [comment]
Same here. Also double-checked that all the required files are in their place.

**Comment by jonbarrow** [comment]
Nimbus has been updated recently and this issue lacks any sort of real details (no crash logs, screenshots, etc.)

I have also mentioned steps to try and resolve this [here](https://github.com/PretendoNetwork/.github/issues/28#issuecomment-1883937063)

Closing due to lack of crash details and Nimbus being updated recently (try again on the latest release)
